package constants

const EXP_STATUS_EXPIRED = 1
const EXP_STATUS_AVAILABLE = 0

const PAYMENT_STATUS_PENDING = 0
const PAYMENT_STATUS_COMPLETED = 1
const PAYMENT_STATUS_CANCELLED = 2

const ORDER_STATUS_PENDING = 0
const ORDER_STATUS_COMPLETED = 1
const ORDER_STATUS_CANCELLED = 2
const ORDER_STATUS_VERIFYING = 3

const WAITING = 0
const COMPLETE = 1

const SIGNUP = 0
const FORGET_PASSWORD = 1

const PROVIDER_EMAIL = "email"
const PROVIDER_GMAIL = "gmail"
